version: 2.1
jobs:
  frontEnd:
    working_directory: ~/project/front-end
    docker:
      - image: circleci/node:10.15.1
    steps:
      - checkout:
          path: ~/project
      - run:
          name: Install front end dependencies
          command: pwd && ls && npm i
      - run:
          name: Execute unit tests
          command: npm test

workflows:
  version: 2
  buildAndTestFE:
    jobs:
      - frontEnd
