version: 2.1
jobs:
  frontEnd:
    working_directory: ~/front-end
    docker:
      - image: circleci/node:10.15.1
    steps:
      - checkout
      - run:
          name: Install front end dependencies
          command: npm i
      - run:
          name: Execute unit tests
          command: npm test

workflows:
  version: 2
  buildAndTestFE:
    jobs:
      - frontEnd
