version: 2.1
jobs:
  frontEnd:
    docker:
      - image: circleci/node:10.15.1
    steps:
      - checkout
      - run:
        name: Install front end dependencies
        command: cd front-end && npm i
      - run:
        name: Execute unit tests
        command: cd front-end && npm test
